adding gallery html and css
KateDietkova/filmoteka-project pull request #4
Opened 2022-11-05 14:17 UTC by ValeriiaMezentseva

2022-11-05 18:16 UTC, ValeriiaMezentseva commented
додала картинки у випадку, якщо ввели неіснуючу назву фільму, і там де, ще нема списку доданих фільмів, але якщо виглядає не ок, то приберу)

2022-11-06 09:03 UTC, KateDietkova commented on src/sass/layouts/gallery.scss
> +  margin-top: 20px;
Прибери, будь ласка,  margin-top: 20px;) Тут список треба відсунути від батьківського елемента, і це треба зробити падінгами секції) Також секції можна додати нижній падінг який йде після пагінації 40px) У цьому списку  margin-bottom: 40px; можна залишити він якраз між сусідніми елементами йде)

2022-11-06 09:04 UTC, KateDietkova commented on src/partials/layouts/gallery.html
> +  <div class="container">
Зміни, будь ласка місцями теги <div class="container"> та <section class="movie-gallery">, спочатку section, а вже в ній контейнер для контенту)

2022-11-06 09:05 UTC, KateDietkova commented on src/partials/layouts/gallery.html
> +<main>
Мейн можна прибрати, бо я вже в index.html його прописала і вньому підключила галерею)

2022-11-06 09:10 UTC, KateDietkova requested changes
Need a few changes

2022-11-06 11:03 UTC, KateDietkova approved these changes

2022-11-06 11:03 UTC, merged