feature/header
KateDietkova/filmoteka-project pull request #9
Opened 2022-11-05 17:34 UTC by YuliiaMakhovska

add header

2022-11-05 19:35 UTC, KateDietkova commented on src/sass/_common.scss
> +.list {
list не потрібно тут прописувати, бо це вже є у плейсхолдерах, тобто в тому селекторі класу, що відноситься до списку, можна просто спочатку прописати %list) Подивись, будь ласка, файл sass/utils/placeholders

2022-11-05 19:37 UTC, KateDietkova commented on src/sass/_common.scss
> +* {
Зверху я скидаю стилі для p та всіх заголовків) Це не обов'язково прописувати

2022-11-05 19:41 UTC, KateDietkova commented on src/sass/layouts/_header.scss
> +    &__library{
Хедером для library займається Антон) Тому стилі для library можна видалити)

2022-11-05 19:52 UTC, KateDietkova commented on src/partials/layouts/header.html
> +          <use href="./images/svg/symbol-defs.svg#icon-film-icon"></use>
Цю svg я вже додавала до спрайту, спрайт знаходиться в images/icons.svg

2022-11-05 19:53 UTC, KateDietkova commented on src/sass/layouts/_header.scss
> +    font-weight: 400;
Якщо значення 400, це можна не вказувати, воно таким встановлюється по дефолту)

2022-11-05 19:54 UTC, KateDietkova commented on src/sass/layouts/_header.scss
> +    color: #FFFFFF;
Колір треба прописати використовуючи змінні, вони знаходяться у sass/utils/variables, прописуємо через var, наприклад color: var(--primary-lighttext-color)

2022-11-05 19:56 UTC, KateDietkova commented on src/sass/layouts/_header.scss
> +    height: 44px;
Висоту кнопки задаємо не за рахунок  height, а за рахунок падінгів)

2022-11-05 19:57 UTC, KateDietkova commented on src/sass/layouts/_header.scss
> +      height: 42px;
Замість висоти, треба проставити падінги)

2022-11-05 19:59 UTC, KateDietkova commented on src/sass/layouts/_header.scss
> +    border: 1px solid var(--primary-lighttext-color);
Сюди можеш додати ще властивість transition: border-color var(--main-effect), background var(--main-effect);

2022-11-05 20:00 UTC, KateDietkova requested changes
Need a few changes

2022-11-06 07:51 UTC, YuliiaMakhovska commented on src/sass/_common.scss
> +* {
якщо не прописую зірочку, тоді повноцінно бордери не видаляються в інпуті, пробувала різні варіанти...

2022-11-06 09:00 UTC, YuliiaMakhovska commented on src/partials/layouts/header.html
> +          <use href="./images/svg/symbol-defs.svg#icon-film-icon"></use>
видалила інший спрайт, перенесла в іконс свгшку

2022-11-06 09:00 UTC, YuliiaMakhovska commented on src/sass/layouts/_header.scss
> +    font-weight: 400;
прибрала

2022-11-06 09:01 UTC, YuliiaMakhovska commented on src/sass/layouts/_header.scss
> +    color: #FFFFFF;
виправила

2022-11-06 09:01 UTC, YuliiaMakhovska commented on src/sass/_common.scss
> +.list {
видалила

2022-11-06 09:04 UTC, YuliiaMakhovska commented on src/sass/layouts/_header.scss
> +    border: 1px solid var(--primary-lighttext-color);
.library-btn:hover,
 .library-btn:focus {
    border-color: var(--primary-accent-color);
    transition: var(--main-effect);
    background: var(--primary-accent-color);
    
}
я нижче додавала при ховері і фокусі

2022-11-06 09:11 UTC, YuliiaMakhovska commented on src/sass/layouts/_header.scss
> +    height: 44px;
виправила

2022-11-06 09:11 UTC, YuliiaMakhovska commented on src/sass/layouts/_header.scss
> +      height: 42px;
виправила

2022-11-06 09:25 UTC, KateDietkova commented on src/sass/_common.scss
> +* {
Там можна було б в інпуті прописати спочатку border: none та outline: none) Але ок, то можна пізніше якщо буде треба пофіксити)

2022-11-06 09:53 UTC, KateDietkova requested changes
need changes

2022-11-06 11:38 UTC, KateDietkova approved these changes, later dismissed

2022-11-06 11:46 UTC, KateDietkova approved these changes

2022-11-06 11:47 UTC, merged